### PR TITLE
Verification of Employment Process

### PR DESCRIPTION
**Pull request by NicholeG**
Add section/language on verification of employment items

### CODE REVIEW

**Comment by NicholeG** [comment]
@therebbie please take a look and let me know your thoughts. TY!

**Review by therebbie — COMMENTED** [review]
Do we want to tell people how they should contact HR with their request?  If we don't add that now, we'll be adding it soon.   I can think of a few ways to notify, but email is likely best as it is most private.  For now I think that means email to @NicholeG but in the future we may wish to have an hr email address ... but we need to be mindful of putting email addresses in public places so they don't attract SPAM.

**Comment by NicholeG** [comment]
I will add that they should email HR. Agree about not showing an actual email though. I get plenty of spam already :)

**Review by therebbie — APPROVED** [review]
Looks good - I presume we will rely on the release form that the vendor (landlord, bank, etc.) provides, right?  That's not stated here, but I think it's perfectly fine as is.  I don't think we need to prepare a release for this eventualty.

**Comment by NicholeG** [comment]
Correct. Most send them along with whatever form they need us to fill out. I agree as well

**Pull request merged**
