### PR TITLE
Create new dir HubSpot

### PR DESCRIPTION
**Pull request by sarahddaily**
Copy content from https://handbook.meltano.com/marketing/marketing-ops/hubspot to dedicated page under /tech-stack because it serves as a better centralized location for all tools the company uses. It has a dedicated page as documentation increases because it is both our CRM and MAP.

### CODE REVIEW

**Comment by sarahddaily** [comment]
deleting the duplicate file under /marketing ops in this PR: https://github.com/meltano/handbook/pull/341

**Comment by sarahddaily** [comment]
@afolson would you mind taking a peak at this for any issues before I merge? TY!

**Comment by afolson** [comment]
@sarahddaily I renamed the folders to play nicely with Jekyll: https://deploy-preview-340--meltano-handbook.netlify.app/company/tech-stack/hubspot/

This doesn't show up in the sidebar yet because it'll take some restructuring of the site to make it happen. I have an action item to fix that at some point 🥺

**Comment by afolson** [comment]
Live link: https://handbook.meltano.com/company/tech-stack/hubspot/

**Pull request merged**
