### PR TITLE
feat: support subcategories, reorganise Engineering Handbook

### PR DESCRIPTION
**Pull request by kgpayne**
There doesn't seem to be a supported way to do subcategories in Jekyll, so I used a workaround using Front Matter `subcategory` values. Bulma (the CSS library we are using) only [supports 2 levels of depth](https://bulma.io/documentation/components/menu/) in `menu` classes, which limits how much subcategorisation we can ultimately do, but 2 is still way better than 1 😅

Did this as I hope `Guilds` will become a subcategory 👍

### CODE REVIEW

**Review by WillDaSilva — COMMENTED** [review]
Looks good.

image

Right now each subcategory has an index page shown underneath the category in the table of contents. This results in each category title being repeated. Would it be possible for the category item in the table of contents to be clickable, and have the index page, rather than listing the index page beneath it?

If this isn't a relatively simple change, I'd say don't bother.

**Comment by kgpayne** [comment]
cc @tayloramurphy as I believe this was something you wanted to be able to do.

**Comment by kgpayne** [comment]
@WillDaSilva 

> Right now each subcategory has an index page shown underneath the category in the table of contents. This results in each category title being repeated. Would it be possible for the category item in the table of contents to be clickable, and have the index page, rather than listing the index page beneath it?
> 
> If this isn't a relatively simple change, I'd say don't bother with it.

I think its possible, but it involves iterating all the matching subcategory items page-urls looking for one ending in `/index` 🤔 We'd then probably want to exclude that item from the list if one was found. Will have a stab, and give up if it isn't easy 👍

Longer-term, I think it'd be better to just move to a more flexible (and more familiar) static site generator, [Sphinx](https://github.com/meltano/handbook/issues/404).

**Comment by kgpayne** [comment]
@WillDaSilva it turned out to be easy 😅👍

**Review by WillDaSilva — APPROVED** [review]

**Pull request merged**
